# Generated by Django 4.1.5 on 2023-01-25 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='lang',
        ),
    ]
